
" vim: set sw=4 ts=4 sts=4 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker:

" Use before config if available {
if filereadable(expand("~/.vim/vimrc.before"))
    source ~/.vim/vimrc.before
endif
" }

" Use bundles config {
if filereadable(expand("~/.vim/vimrc.bundles"))
    source ~/.vim/vimrc.bundles
endif
" }

" Use spf13 config if available {
if filereadable(expand("~/.vim/vimrc.spf13"))
    source ~/.vim/vimrc.spf13
    " try
    " catch /^Vim\%((\a\+)\)\=:E185/	" catch E185: Cannot find color scheme 'solarized'
    "     " Error detected while processing /home/dakeng/.vim/vimrc.spf13:
    "     " line  185:
    "     " E185: Cannot find color scheme 'solarized'
    " endtry
endif
" }

" Use local vimrc if available {
if filereadable(expand("~/.vim/vimrc.fork"))
    source ~/.vim/vimrc.fork
endif
" }

" Use user vimrc if available {
if filereadable(expand("~/.vim/vimrc.user"))
    source ~/.vim/vimrc.user
endif
" }

" Use local vimrc if available {
if filereadable(expand("~/.vim/vimrc.local"))
    source ~/.vim/vimrc.local
endif
" }

" Use local gvimrc if available and gui is running {
if has('gui_running')
    if filereadable(expand("~/.vim/gvimrc.local"))
        source ~/.vim/gvimrc.local
    endif
endif
" }

