#!/usr/bin/env bash

# Based off:
# https://www.if-not-true-then-false.com/2010/install-virtualbox-guest-additions-on-fedora-centos-red-hat-rhel/

sudo dnf update && sudo dnf upgrade
sudo dnf install @development-tools
sudo dnf install vim-enhanced
sudo dnf update kernel*
sudo dnf install gcc kernel-devel kernel-headers dkms make bzip2 perl
export KERN_DIR=/usr/src/kernels/`uname -r`
/run/media/hipe/VBOXADDITIONS_5.1.8_111374/VBoxLinuxAdditions.run 
